In [2]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [3]:
import os
import pickle
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from pymoo.indicators.hv import Hypervolume

from util import natural_key, load_yaml

In [4]:
def load_pareto_history(filepath="pareto_history.pkl"):
    """
    Carga el archivo pickle que contiene fronts_history.
    Devuelve un dict: {generacion: {nivel_frente: [registros...]}}
    """
    with open(filepath, "rb") as f:
        history = pickle.load(f)
    return history

In [5]:
def pareto_history_to_df(filepath="pareto_history.pkl", generation=None):
    """
    Convierte la historia de Pareto guardada en filepath en un DataFrame
    para la generación 'generation', con columnas:
        generation, front_level, accuracy, params, inference_time
    """
    history = load_pareto_history(filepath)
        
    if generation is None:
        generation = max(history.keys())
        
    gen_dict = history[generation]
    records = []
    for level, recs in gen_dict.items():
        # saltamos la métrica hypervolume
        if level == "hypervolume":
            continue
        for rec in recs:
            records.append({
                "id":             rec["id"],
                "generation":      generation,
                "front_level":     level,
                "accuracy":        rec["accuracy"],
                "params":          rec["params"],
                "inference_time":  rec["inference_time"]
            })
    return pd.DataFrame(records)

In [6]:
def archive_to_df(experiment_path: str, archive_subdir: str = "archive") -> pd.DataFrame:
    """Load training metrics from the archive directory into a DataFrame.

    Each folder inside ``archive_subdir`` should contain a ``training_params.txt``
    file with keys such as ``fitness_metric``, ``cuda_inference_time`` and
    ``total_params``. The value for ``fitness_metric`` is taken from the metric
    name specified in that file.

    Parameters
    ----------
    experiment_path : str
        Path to the root experiment directory.
    archive_subdir : str, optional
        Name of the subdirectory that stores archived results. Defaults to
        ``"archive"``.

    Returns
    -------
    pandas.DataFrame
        DataFrame with columns ``id``, ``fitness_metric``, ``cuda_inference_time``
        and ``total_params`` for all archived runs.
    """

    archive_dir = os.path.join(experiment_path, archive_subdir)
    if not os.path.isdir(archive_dir):
        raise FileNotFoundError(f"Archive folder not found at {archive_dir}")

    records = []
    for folder in sorted(os.listdir(archive_dir), key=natural_key):
        params_file = os.path.join(archive_dir, folder, "training_params.txt")
        if not os.path.isfile(params_file):
            continue

        params = load_yaml(params_file)
        metric_key = params.get("fitness_metric")
        if metric_key is None:
            continue

        fitness_value = params.get(metric_key)
        cuda_time = params.get("cuda_inference_time")
        tot_params = params.get("total_params")

        records.append(
            {
                "id": folder,
                "fitness_metric": fitness_value,
                "cuda_inference_time": cuda_time,
                "total_params": tot_params,
            }
        )

    return pd.DataFrame(records)

In [7]:
path_archive = "experiment_cifar10_nsgaX/exp1_repeat_1"
df_archive = archive_to_df(path_archive)
df_archive.shape

(57, 4)

In [8]:
df_archive

       id  fitness_metric  cuda_inference_time  total_params
0     3_5            72.0          1350.355148        928106
1   13_16            68.8          4329.228401        483466
2   13_19            70.0          8633.565903        368394
3    14_2            64.2          3284.907341        502634
4    14_5            71.5          1269.936562        863786
5    14_6            70.6          9605.908394        382826
6   14_12            72.5          3805.470467        613258
7   18_18            74.3          1395.940781       1283082
8    19_1            68.6         22642.707825        242154
9    22_8            66.8         15741.825104        212362
10  22_12            50.8         10984.992981         52746
11  22_14            58.9         15058.159828        102922
12  22_15            52.6         17338.371277         52362
13  22_17            57.1          9181.404114         93898
14   23_7            59.1         12009.739876        194442
15   24_5            52.5         18106.412888         42122
16  24_13            68.4          5515.885353        378346
17   26_0            56.1         23227.334023         49194
18  26_10            70.7          7236.313820        580266
19  26_15            70.9         11322.641373        365962
20   27_5            54.5         20586.037636         63370
21  27_19            60.1         16875.195503         77098
22  28_14            70.0          5611.824989        424330
23  29_13            66.3          1250.457764        725386
24   30_2            69.4          7760.810852        310282
25   30_5            60.7         12455.987930        176330
26  30_11            54.1         18943.858147         35370
27  30_12            50.7         16134.071350         41802
28  30_16            58.9          1575.279236        458346
29   32_5            72.6         23340.320587        302090
30  33_15            58.2         11570.024490        221898
31   34_0            56.7         30797.815323         68426
32   34_8            70.1         27747.726440        272554
33   35_0            63.1         14622.807503        123114
34  35_10            73.0          3875.255585        636234
35  35_17            73.3          1182.770729       1052586
36   36_8            65.3         14259.862900        206122
37   37_3            73.9          7482.266426        806314
38   37_9            74.6          1260.209084       1747562
39  37_18            71.9          1242.089272        978218
40  40_10            70.8          9296.751022        429994
41  40_17            74.5          3934.407234       1191754
42   42_8            72.7          1122.832298       1679882
43   42_9            76.5          4144.501686        982634
44  42_10            74.3          7617.783546        901290
45  42_18            69.3         12536.954880        282314
46  43_11            65.8          3745.961189        601450
47  43_12            63.5          2991.509438        297418
48   44_1            72.2          1081.800461       2145802
49   45_1            55.5         21260.046959         61066
50   45_2            67.1         10186.862946        247530
51  45_10            67.6          1260.685921        620330
52  45_19            58.5         14293.074608         74570
53  46_14            72.5          1107.096672       1659242
54  48_12            71.2         21081.185341        509706
55  48_16            71.9          1043.987274       1863658
56  49_18            75.6          9728.360176        718154

In [9]:
pkl_path = os.path.join(path_archive, "pareto_history.pkl")
df_history = pareto_history_to_df(pkl_path)
df_history = df_history[df_history["front_level"] == 1]

In [12]:
# check if there are some ids that has the same values in accuracy, params and inference_time, in df_history, if so, remove the ones that are not in df_archive
duplicated_rows = df_history[df_history.duplicated(subset=['accuracy', 'params', 'inference_time'], keep=False)]
if not duplicated_rows.empty:
    print("Duplicated rows found")
    archive_ids = set(df_archive['id'])
    rows_to_remove = duplicated_rows[~duplicated_rows['id'].isin(archive_ids)]
    if not rows_to_remove.empty:
        print(f"Removing {len(rows_to_remove)} rows")
        df_history = df_history.drop(rows_to_remove.index)

Duplicated rows found
Removing 41 rows

In [13]:
df_history

       id  generation  front_level  accuracy     params  inference_time
3   13_16          49            1      68.8   483466.0     4329.228401
4   13_19          49            1      70.0   368394.0     8633.565903
5   14_12          49            1      72.5   613258.0     3805.470467
6    14_2          49            1      64.2   502634.0     3284.907341
7    14_5          49            1      71.5   863786.0     1269.936562
8    14_6          49            1      70.6   382826.0     9605.908394
9   18_18          49            1      74.3  1283082.0     1395.940781
10   19_1          49            1      68.6   242154.0    22642.707825
15  22_12          49            1      50.8    52746.0    10984.992981
16  22_14          49            1      58.9   102922.0    15058.159828
17  22_15          49            1      52.6    52362.0    17338.371277
18  22_17          49            1      57.1    93898.0     9181.404114
20   22_8          49            1      66.8   212362.0    15741.825104
22   23_7          49            1      59.1   194442.0    12009.739876
25  24_13          49            1      68.4   378346.0     5515.885353
26   24_5          49            1      52.5    42122.0    18106.412888
29   26_0          49            1      56.1    49194.0    23227.334023
30  26_10          49            1      70.7   580266.0     7236.313820
32  26_15          49            1      70.9   365962.0    11322.641373
34  27_19          49            1      60.1    77098.0    16875.195503
35   27_5          49            1      54.5    63370.0    20586.037636
37  28_14          49            1      70.0   424330.0     5611.824989
40  29_13          49            1      66.3   725386.0     1250.457764
41  30_11          49            1      54.1    35370.0    18943.858147
42  30_12          49            1      50.7    41802.0    16134.071350
44  30_16          49            1      58.9   458346.0     1575.279236
45   30_2          49            1      69.4   310282.0     7760.810852
46   30_5          49            1      60.7   176330.0    12455.987930
48   32_5          49            1      72.6   302090.0    23340.320587
50  33_15          49            1      58.2   221898.0    11570.024490
51   34_0          49            1      56.7    68426.0    30797.815323
52   34_8          49            1      70.1   272554.0    27747.726440
53   35_0          49            1      63.1   123114.0    14622.807503
54  35_10          49            1      73.0   636234.0     3875.255585
56  35_17          49            1      73.3  1052586.0     1182.770729
60   36_8          49            1      65.3   206122.0    14259.862900
61  37_18          49            1      71.9   978218.0     1242.089272
62   37_3          49            1      73.9   806314.0     7482.266426
63   37_9          49            1      74.6  1747562.0     1260.209084
66    3_5          49            1      72.0   928106.0     1350.355148
67  40_10          49            1      70.8   429994.0     9296.751022
68  40_17          49            1      74.5  1191754.0     3934.407234
69  42_10          49            1      74.3   901290.0     7617.783546
70  42_18          49            1      69.3   282314.0    12536.954880
72   42_8          49            1      72.7  1679882.0     1122.832298
73   42_9          49            1      76.5   982634.0     4144.501686
74  43_11          49            1      65.8   601450.0     3745.961189
75  43_12          49            1      63.5   297418.0     2991.509438
77   44_1          49            1      72.2  2145802.0     1081.800461
79   45_1          49            1      55.5    61066.0    21260.046959
80  45_10          49            1      67.6   620330.0     1260.685921
82  45_19          49            1      58.5    74570.0    14293.074608
83   45_2          49            1      67.1   247530.0    10186.862946
84  46_14          49            1      72.5  1659242.0     1107.096672
87  48_12          49            1      71.2   509706.0    21081.185341
89  48_16          49            1      71.9  1863658.0     1043.987274
90  49_18          49            1      75.6   718154.0     9728.360176

In [14]:
# check if there are any different ids in the archive and history
archive_ids = set(df_archive["id"])
history_ids = set(df_history["id"])
print(f"Archive IDs: {len(archive_ids)}")
print(f"History IDs: {len(history_ids)}")
print(f"Different IDs: {len(archive_ids - history_ids)}")
# check the values of the ids that are in the archive but not in the history
diff_ids = archive_ids - history_ids
print("Different IDs:", diff_ids)

Archive IDs: 57
History IDs: 57
Different IDs: 0
Different IDs: set()